VENDOR_COLUMN_MAPPING = {
    "DisplayName": "DisplayName",
    "CompanyName": "CompanyName",
    "PrintOnCheckName": "PrintOnCheckName",
    "Active": "Active",
    "TaxIdentifier": "TaxIdentifier",
    "Vendor1099": "Vendor1099",
    "Balance": "Balance",
    "PrimaryEmailAddr.Address": "PrimaryEmailAddr.Address",
    "PrimaryPhone.FreeFormNumber": "PrimaryPhone.FreeFormNumber",
    "AlternatePhone.FreeFormNumber": "AlternatePhone.FreeFormNumber",
    "Mobile.FreeFormNumber": "Mobile.FreeFormNumber",
    "Fax.FreeFormNumber": "Fax.FreeFormNumber",
    "WebAddr.URI": "WebAddr.URI",
    "GivenName": "GivenName",
    "MiddleName": "MiddleName",
    "FamilyName": "FamilyName",
    "BillAddr.Line1": "BillAddr.Line1",
    "BillAddr.Line2": "BillAddr.Line2",
    "BillAddr.Line3": "BillAddr.Line3",
    "BillAddr.City": "BillAddr.City",
    "BillAddr.Country": "BillAddr.Country",
    "BillAddr.CountrySubDivisionCode": "BillAddr.CountrySubDivisionCode",
    "BillAddr.PostalCode": "BillAddr.PostalCode",
    "CurrencyRef.value": "CurrencyRef.value",
    "CurrencyRef.name": "CurrencyRef.name"
}
